username = input("Heyo kid. What's your name? ")
print(f"Nice name, {username}")
uppername = username.upper()
print(f"Did you know your name has {len(username)} letters, {uppername}?")
noun = input("Please enter a noun for MadLibs: ")
verb = input("Please enter a verb for MadLibs in gerund style (ends with ing, ie \'swinging\': ")
adjective = input("Please enter an adjective for MadLibs: " )
print(f"Did you hear that a {adjective} {noun} was arrested for {verb} in Montreal?")
